name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-cv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "25.10.4"

      - name: Compile latest CV
        run: nextflow run maxulysse/compile-latex -r 3.0.0 -profile docker --input CV-MGarcia-latest --pictures pictures/ --biblio biblio.bib --outdir .
